### ISSUE TITLE
"Unexpected null value" error when we set bottomSheetModalBackgroundColor

### ISSUE THREAD

**Issue by mcssym** [rydmike/flex_color_scheme#106]
When we set `bottomSheetModalBackgroundColor: SchemeColor.surface` we have an error `Unexpected null value`. I check the code when the error is thrown 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/116432410/209329897-343e83ae-39f4-49ba-b402-3fca03ddba98.png">
in file `lib\src\flex_color_scheme.dart` it seems if `bottomSheetModalBackgroundColor` is set then it tries to get the color from `bottomSheetBackgroundColor` instead of `bottomSheetModalBackgroundColor`.

I am using the version 6.1.1 and definig a theme data with `FlexThemeData.dark` .

**Comment by rydmike** [comment]
Thanks for the fix @mcssym. Clearly a copy-paste error. Also not caught by tests because the case was tested with both backgrounds set in the same tests, which effectively bypassed the modal that was null. Added separate test for this bug as well, that was triggered prior to the the fix.
