### ISSUE TITLE
funny shadow quirk

### ISSUE THREAD

**Issue by fredgrott** [rydmike/flex_color_scheme#111]
When using FCS 6 in a mod of the material 3 demo shadow and outline colors under dark do not switch. Here is a link to the sceenshot via google photos.

[shadow](https://photos.google.com/photo/AF1QipPHYV0TZxF0j_tIqkPbgIT-4gjAzSlJxcdfOp6i)

Not a FCS problem per say, just something to be aware of on flutter 3.7.0.1.4-pre

**Comment by rydmike** [comment]
Sounds interesting, would love to take a closer look at what's going on, but I was unable to open the Google photos link you sent.

**Comment by rydmike** [comment]
Closing issue due to no follow-up response. It will be opened again if there is a follow up response that warrants further investigation. Thank you for your issue report.
