### ISSUE TITLE
Persistent Theme

### ISSUE THREAD

**Issue by overhaul1** [rydmike/flex_color_scheme#13]
Thank you for this amazing package, i have read your blog as well as readme but didn't found any way to persist theme or theme settings in android or web. Do you have any plans to add em or i'll need to use shared prefs?

**Comment by rydmike** [comment]
Hi @Overhaul1 thanks for your question. FlexColorScheme is more of a variant of Flutter's ThemeData and ThemeData.from, and as such does not deal with serialization and storage of the data itself.

It was on the "maybe" list of things to add, but I am leaning more towards "probably not". 

------

This is what I wrote about it in the [change log](https://github.com/rydmike/flex_color_scheme/blob/master/CHANGELOG.md): 

- **Serialization of FlexColorScheme**  
  Including built-in serialization of FlexColorScheme, and its key classes has been suggested. I consider
  `FlexColorScheme` to be functionally on a level similar to `ColorScheme`, and therefore it should not cover 
  serialization of itself. Serialization have to deal with a lot of potential failure points that I think should
  not have to be a concern in this type of component. I am not planning to add it, not yet at least, I might
  reconsider this later.
  
  My recommendation for saving the state of a `FlexColorScheme` is to include values for its settings that you 
  use in your implementation in other models in your application, like an "AppSettings" model or similar. 
  You probably serialize and store such data already, perhaps with shared preferences, hive, get_storage or 
  some other solution. Include the values you need for your `FlexColorScheme` implementation in your stored settings
  and then use those values to restore your `FlexColorScheme` configuration and theme. This way, your implementation
  also remain in control of what it needs to store and restore.  

----

I do however plan to add a new more advanced example to the package bundled samples. This example will use Riverpod for state management and persist the selected theme and all its configuration options with Hive, in a way that works on all current Flutter platforms.

**Comment by Overhaul1** [comment]
Any eta for this advance example?

**Comment by rydmike** [comment]
I'm working on pulling it out of another larger code base (almost done) where I am using it. I want to include it (bundle it) with the next release of the package. Sorry I can't commit to a deadline for open source side projects, as I don't want to promise something that does not happen when I said it would. 😃

**Comment by rydmike** [comment]
@overhaul1 Version 4 has been released, its examples contains demonstration on how to persist themes using FlexColorScheme with both Hive and SharedPreferences. Closing this issue! 😃 

The demonstrated solution is very general and can be used for persisting other settings too, not just FlexColorScheme settings.
