### ISSUE TITLE
Glitches in highlighting effect on mouse hover over FlexThemeModeSwitch/FlexThemeModeOptionButton in ver. 7.0.4

### ISSUE THREAD

**Issue by coderaper** [rydmike/flex_color_scheme#143]
This issue was already reported in #136, which has already been given fixed and closed status.

What has actually been fixed from the bugs mentioned in #136 is the default background colour of the switch buttons . The problem of the layer with the hover colour not covering the whole button remains. I reported this, but I assume it went unnoticed because the issue was already closed. Since I cannot reopen the issue, I have decided to create a new one.

How to reproduce:

Open the current version of the All Themes Demo web application, which is currently 7.0.4:

https://rydmike.com/flexcolorscheme/allthemes-v7/#/

To make the problem more obvious, select a dark theme and place the mouse cursor over the LIGHT button of the Theme Mode switch:

![All_Themes_v7 0 4_1](https://user-images.githubusercontent.com/36661498/235206890-fecdfdec-f226-4a27-ac32-0557561af272.png)

To prove that the problem didn't exited in 6.x versions, open All Themes Demo web application, build with 6.1.1 and repeat the above steps:

https://rydmike.com/flexcolorscheme/allthemes-v6/#/

![All_Themes_v6 1 1_1](https://user-images.githubusercontent.com/36661498/235206992-2747f8f1-64e9-449d-a3d8-71393d69b239.png)

I have already provided a patch in #136 that seems to fix this problem. See there screenshots taken with the original version and with the patch applied.

For the sake of completeness, here is a link to the patch again:

https://gist.github.com/coderaper/f80bb44919dc03448a9857e678d26b5b

**Comment by rydmike** [comment]
Thanks @coderaper and sorry I completely missed the size gap, only noticed the color on previous fix. Fix with this inbound.

**Comment by rydmike** [comment]
Version 7.0.5 released https://pub.dev/packages/flex_color_scheme/changelog

New WEB versions building.

**Comment by rydmike** [comment]
No feedback in 1 week, closing as fixed, and it should be, but feel free to let me know if it is not.
