### ISSUE TITLE
AppBar color different from playground

### ISSUE THREAD

**Issue by solaristhesun** [rydmike/flex_color_scheme#154]
I created a new flutter app using "flutter create", added flex_color_scheme 7.1.1 and copied a theme code from the playground. Why does the color of the AppBar not match?

![playground](https://github.com/rydmike/flex_color_scheme/assets/473078/7f59bb39-f076-43d0-a6db-4d60bcf968fd)

**Comment by solaristhesun** [comment]
Nevermind.

**Comment by rydmike** [comment]
The app set a color on widget level somewhere overriding the themed color?
Just curious what you found...  😄

**Comment by solaristhesun** [comment]
Yes, exactly. The flutter default application sets the AppBar background to inversePrimary. But: I tried to create this minimal example because I noticed a different AppBar color in another App that uses a "customizable" scheme. I might come back to you if I have some more time to look into it.
