### ISSUE TITLE
Make it easy to choose the theme in the Playground app

### ISSUE THREAD

**Issue by arnab** [rydmike/flex_color_scheme#163]
First, thanks for making an excellent plugin!

I often need to look at the effective colors tab in [the playground](https://rydmike.com/flexcolorscheme/themesplayground-v6/#/) to determine what to pick for a certain UI/UX.

I already have an app that uses FlexColorScheme for a few months now. But every time I go to the playground, I have to manually hunt around for the theme my app uses (e.g. `blueWhale`). 

This can only be done visually by clicking around, it looks to me. It would be nice to:

1. see the theme names in a clickable-list, or choose the theme using a drop-down (where you can type the names).
2. additionally, if the name is in the URL, it would be super easy to switch to it.

**Comment by rydmike** [comment]
Hi @arnab,

Thanks for your improvement proposals.

**Option 1** is already available, partially at least. You can go to **Theme Colors** panels and use the dropdown there to select the color scheme in a drop-down. It is not searchable though, as it uses the old style M2 dropdown. But at least it shows the names, so it can be a bit easier to find a specific one via it.

I can probably change the M2 dropdown relatively easily to the newer M3 dropdown, that also allows you to search by name. I will look into that for a future release.

https://github.com/rydmike/flex_color_scheme/assets/39990307/01be0091-614b-4d38-a12f-43c3caca63ed

**Option 2** Is certainly also a possibility, but it will however not happen until the Themes Playground is reborn in new version that actually has multiple pages. Even then, I'm not so sure that having the color scheme selection as part of the page route parameter is really that useful, but perhaps 

What it sounds more like is that you want to be able to persist multiple different configs, name them and open them again later, possibly also export/import configs, and probably also share configs within a team, or potentially even via a public config link. Those things are in the scope for a major refactor/rewrite of the Playground companion app to FlexColorScheme.

----

For reference, you can read some more info about how the Playground started and why it has a rather humble and simple architecture and what my thoughts and plans around it are going forward here: https://docs.flexcolorscheme.com/playground#background

**Comment by arnab** [comment]
Thanks for the super quick response. Here are my thoughts/questions:

> Option 1 is already available, partially at least. You can go to Theme Colors panels and use the dropdown there to select the color scheme in a drop-down. It is not searchable though, as it uses the old style M2 dropdown. But at least it shows the names, so it can be a bit easier to find a specific one via it.

I am at https://rydmike.com/flexcolorscheme/themesplayground-v6/#/. And perhaps I am not looking at the right place, but I don't see the names or a drop-down to select the themes.

Here is what I see:

<img width="1253" alt="theme-colors" src="https://github.com/rydmike/flex_color_scheme/assets/57342/9d3d54a3-c08f-44d5-b3ac-acc3866a0f03">

I agree seeing the names along with the theme-colors would also alleviate this issue, as I can just use my browser to search for a name.

**Comment by arnab** [comment]
Re: the major refactor/rewrite of the Playground companion app to FlexColorScheme. That sounds excellent! We will wait for that!

Meanwhile if I can see the names in the browser that immediately solves this issue in a round-about way. Let me know if there is a quick way to turn that on (perhaps it's some configuration)?

**Comment by rydmike** [comment]
This is as easy as it will get in already version 7 and later, which is demonstrated in explanations above. Closing the issue. Future version like next gen, might provide additional methods for choosing the the color scheme and also storing different named ones, and export/import as well.
