### ISSUE TITLE
Images are not loading properly. ( Working fine when using VPN )

### ISSUE THREAD

**Issue by RR-Reddy** [rydmike/flex_color_scheme#187]
Country : India 
VPN Country : Singapore ( this time worked)

<img width="1429" alt="Screenshot 2023-09-06 at 8 29 42 AM" src="https://github.com/rydmike/flex_color_scheme/assets/32235964/644ccaa3-8f29-4a94-be3a-71180088ac78">
<img width="1429" alt="Screenshot 2023-09-06 at 8 26 07 AM" src="https://github.com/rydmike/flex_color_scheme/assets/32235964/12c90b8a-1b39-499b-9c58-c89fff15e95c">

**Comment by rydmike** [comment]
Sorry to hear that @RR-Reddy.

Not so sure I can do much about it. The documentation site's content is hosted directly on GitHub and served as a web page by docs.page.

I could ask them if docs.page have heard of this issue before. But it is a free service, so I doubt it would be a priority for them to look into.

Just out of curiosity, what VPN are you using that is having this issue? Maybe the VPN is not working properly or doing something unusual. 

If I enable my VPN client I still see the images.

/Mike

**Comment by RR-Reddy** [comment]
@rydmike 
Images are loaded fine now. looks like some network issue.

Thanks for quick response.
