### ISSUE TITLE
Can't copy all theme values from themeColors in themesplayground? This was possible before, and it worked

### ISSUE THREAD

**Issue by laterdayi** [rydmike/flex_color_scheme#209]
Can't copy all theme values from themeColors in themesplayground? This was possible before, and it worked

**Comment by laterdayi** [comment]
![图片](https://github.com/rydmike/flex_color_scheme/assets/122137647/6a27833f-290f-4456-a26e-918844543e7c)

**Comment by laterdayi** [comment]
Maybe I forgot. Yes, that's it. I remember it was there before. Thank you

**Comment by rydmike** [comment]
You can also copy a color by tapping on any color box in the Effective Colors panel. 

Those color boxes where also on some other panels before. In case it was not any of the above one, maybe that is the one you were thinking of?

![Screenshot 2023-10-25 at 14 23 31](https://github.com/rydmike/flex_color_scheme/assets/39990307/ace7a385-0b1e-40e2-847b-c9784fbeb58d)
