### ISSUE TITLE
How to set status bar icon black ?

### ISSUE THREAD

**Issue by qianciling** [rydmike/flex_color_scheme#215]
like [example](https://docs.flexcolorscheme.com/examples)  is this 
![Screenshot_20240102_001553](https://github.com/rydmike/flex_color_scheme/assets/7857623/e3cec1e9-7c1f-4a09-a2ff-6d8226485811)

but [ThemeDemo](https://github.com/rydmike/theme_demo)
![Screenshot_20240102_001210](https://github.com/rydmike/flex_color_scheme/assets/7857623/c3418e4e-ee54-4173-8ea1-0e61dc10e936)

**Comment by qianciling** [comment]
sorry , That is  RedMi phone bug! close

**Comment by rydmike** [comment]
Hi @qianciling, sorry for taking so long to getting back to you. I'm glad that you found the issue though! 👍🏻 💙
