### ISSUE TITLE
uses-material-design: true should be false or removed

### ISSUE THREAD

**Issue by gslender** [rydmike/flex_color_scheme#24]
As there are no icons being used, and/or the main app (not library) should really be allowed to define this setting, please remove the uses-material-design: true from the primary pubspec.

**Comment by rydmike** [comment]
Thanks @gslender good catch. It has been removed in 4.2.0 branch, it will no longer be present in next release on pub.dev when 4.2.0 is ready to be published.

**Comment by rydmike** [comment]
@gslender for info, this has been addressed and is now also included in 4.2.0 version via https://github.com/rydmike/flex_color_scheme/pull/30 that is now published on pub at https://pub.dev/packages/flex_color_scheme/changelog

Closing this issue as solved. :)
