### ISSUE TITLE
Expect support in v8 to set the bottomNavigationBar background color to transparent instead of the default white

### ISSUE THREAD

**Issue by maxfrees** [rydmike/flex_color_scheme#258]
Expect support in v8 to set the bottomNavigationBar background color to transparent instead of the default white

![image](https://github.com/user-attachments/assets/81579aed-c010-420d-b773-de73626de363)

Although custom can be achieved, but this way there is a flash screen problem

```
Scaffold(
      appBar: const AppBar(),
      bottomNavigationBar: SafeArea(
      child: Container(
        decoration: BoxDecoration(
          color: Theme.of(context).colorScheme.surface,
          borderRadius: BorderRadius.circular(12),
        ),
        margin: EdgeInsets.only(left: 38, right: 38, bottom: 7),
        padding:EdgeInsets.symmetric(horizontal: AppTheme.padding, vertical: 4),
        child: child,
      ),
    );
      ),
```

https://github.com/user-attachments/assets/bece8449-4ae3-45c7-af2a-d85f4b356b9f

Expectations can be set from a theme setting point of view， bottomNavigationBar background color to transparent

**Comment by rydmike** [comment]
Can you please provide a minimum reproduction sample where this is not working? Because as far as I can see this is working fine and as intended already.

You can theme both `BottomNavigationBar` and `NavigationBar` to be transparent using the `bottomNavigationBarOpacity` and `navigationBarOpacity` in `FlexSubThemesData` by setting their values to zero. This has been available since version 6 at least, maybe even much earlier, I did not check 😄 

In version 8 (8.0.0-dev.1) you can additionally select the `SchemeColor.transparent` as their background color. The opacity value does not matter then, they are always fully transparent then.

## Demo

https://github.com/user-attachments/assets/ba0d1e33-3545-40e3-b93e-cd3efc4ecbb5


## Example config code

```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

/// The [AppTheme] defines light and dark themes for the app.
///
/// Theme setup for FlexColorScheme package v8.
/// Use same major flex_color_scheme package version. If you use a
/// lower minor version, some properties may not be supported.
/// In that case, remove them after copying this theme to your
/// app or upgrade package to version 8.0.0-dev.1.
///
/// Use in [MaterialApp] like this:
///
/// MaterialApp(
///  theme: AppTheme.light,
///  darkTheme: AppTheme.dark,
///  :
/// );
sealed class AppTheme {
  // The defined light theme.
  static ThemeData light = FlexThemeData.light(
    scheme: FlexScheme.blue,
    subThemesData: const FlexSubThemesData(
      // Do this
      bottomNavigationBarOpacity: 0.0,
      navigationBarOpacity: 0.00,
      // OR this (both at same time works too)
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.transparent,
      navigationBarBackgroundSchemeColor: SchemeColor.transparent,
    ),
  );
  // The defined dark theme.
  static ThemeData dark = FlexThemeData.dark(
    scheme: FlexScheme.blue,
    subThemesData: const FlexSubThemesData(
      bottomNavigationBarOpacity: 0.0,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.transparent,
      navigationBarOpacity: 0.00,
      navigationBarBackgroundSchemeColor: SchemeColor.transparent,
   ),
 );
}
```

**Comment by maxfrees** [comment]
@rydmike HI, thank you for your help, I provide a minimal reproduction product, 
[test.zip](https://github.com/user-attachments/files/17468881/test.zip)

https://github.com/user-attachments/assets/c1f96796-91b9-496b-8006-6425d48f6f53

**Comment by rydmike** [comment]
Hi @maxfrees,

Thanks for the example. You are not actually using the `BottomNavigationBar` or the `NavigationBar` components in the sample provided. The theming affect only their backgrounds.

The property in `Scaffold` called `bottomNavigationBar` is just as a slot for any widget, what you put in it is up to you, like in this case with your custom one. Only if you put a `BottomNavigationBar`(M2 style) or `NavigationBar` (M3 style) do the properties have any impact, and works by making **their** backgrounds semi or fully transparent.

Theming properties for `BottomNavigationBar` or `NavigationBar` only affect their properties, nothing in `Scaffold`.

You did enable edge-to-edge and also make the system bottom navigation bar transparent on Android, via:

```dart
return AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(
        context,
        systemNavBarStyle: FlexSystemNavBarStyle.transparent,
      ),

```

But that is another topic and not related to the `BottomNavigationBar`, but it makes the system nav bar (below space for bottom nav bar,. you custom one or the ones from Flutter) transparent and screen fill the entire area even behind system nav bar and also top status bar (above Flutter's AppBar), so we can see when things scroll behind them too, if nothing covers them, like in this example.

I can't really see any major flashing on a Pixel 7 Pro emulator. There is odd jumping of the `TextField`, but that is just Flutter's normal a bit crappy behavior. I think there are some Flutter issues about it.

This would look the same if you remove `FlexColorScheme` and just set the transparent system navbar and edge-to-edge mode with SystemChrome calls.


https://github.com/user-attachments/assets/63e68f6c-634a-4b9a-baa2-c1e0bc4addff


I tweaked the example a bit, it does not really change anything:

```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: FlexThemeData.light(
          scheme: FlexScheme.blue,
          useMaterial3: true,
          appBarOpacity: 0.94,
          subThemesData: const FlexSubThemesData(
            inputDecoratorBorderType: FlexInputBorderType.outline,
            inputDecoratorRadius: 12,
          )),
      darkTheme: FlexThemeData.dark(
          scheme: FlexScheme.blue,
          useMaterial3: true,
          appBarOpacity: 0.92,
          subThemesData: const FlexSubThemesData(
            inputDecoratorBorderType: FlexInputBorderType.outline,
            inputDecoratorRadius: 12,
          )),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  Widget build(BuildContext context) {
    final double topPadding =
        MediaQuery.paddingOf(context).top + kToolbarHeight;
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: FlexColorScheme.themedSystemNavigationBar(
        context,
        systemNavBarStyle: FlexSystemNavBarStyle.transparent,
      ),
      child: Scaffold(
        extendBody: true,
        extendBodyBehindAppBar: true,
        appBar: AppBar(
          title: Text(title),
        ),
        bottomNavigationBar: SafeArea(
          child: Container(
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.surface,
              borderRadius: BorderRadius.circular(12),
              boxShadow: [
                BoxShadow(
                    color: Theme.of(context)
                        .colorScheme
                        .outlineVariant
                        .withOpacity(0.5),
                    blurRadius: 12),
              ],
            ),
            margin: const EdgeInsets.only(left: 38, right: 38, bottom: 7),
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 4),
            child: Row(
              children: [
                FilledButton(onPressed: () {}, child: const Text('add')),
                FilledButton(onPressed: () {}, child: const Text('add')),
              ],
            ),
          ),
        ),
        body: CustomScrollView(
          slivers: [
            SliverToBoxAdapter(
              child: Column(
                children: [
                  SizedBox(height: topPadding),
                  const ListTile(title: Text('Item more text 1')),
                  const ListTile(title: Text('Item more text 2')),
                  const ListTile(title: Text('Item more text 3')),
                  const ListTile(title: Text('Item more text 4')),
                  const ListTile(title: Text('Item more text 5')),
                  const ListTile(title: Text('Item more text 6')),
                  const ListTile(title: Text('Item more text 7')),
                  const ListTile(title: Text('Item more text 8')),
                  const ListTile(title: Text('Item more text 9')),
                  const ListTile(title: Text('Item more text 10')),
                  const ListTile(title: Text('Item more text 11')),
                  const ListTile(title: Text('Item more text 12')),
                  const ListTile(title: Text('Item more text 13')),
                  const ListTile(title: Text('Item more text 14')),
                  const ListTile(title: Text('Item more text 15')),
                  const ListTile(title: Text('Item more text 16')),
                  const ListTile(title: Text('Item more text 17')),
                  const ListTile(title: Text('Item more text 18')),
                ],
              ),
            ),
            const SliverToBoxAdapter(
              child: Padding(
                padding: EdgeInsets.all(8.0),
                child: TextField(),
              ),
            ),
            const SliverToBoxAdapter(
              child: SizedBox(height: 100),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by maxfrees** [comment]
> Hi @maxfrees,
> 
> Thanks for the example. You are not actually using the `BottomNavigationBar` or the `NavigationBar` components in the sample provided. The theming affect only their backgrounds.
> 
> The property in `Scaffold` called `bottomNavigationBar` is just as a slot for any widget, what you put in it is up to you, like in this case with your custom one. Only if you put a `BottomNavigationBar`(M2 style) or `NavigationBar` (M3 style) do the properties have any impact, and works by making **their** backgrounds semi or fully transparent.
> 
> Theming properties for `BottomNavigationBar` or `NavigationBar` only affect their properties, nothing in `Scaffold`.
> 
> You did enable edge-to-edge and also make the system bottom navigation bar transparent on Android, via:
> 
> ```dart
> return AnnotatedRegion<SystemUiOverlayStyle>(
>       value: FlexColorScheme.themedSystemNavigationBar(
>         context,
>         systemNavBarStyle: FlexSystemNavBarStyle.transparent,
>       ),
> ```
> 
> But that is another topic and not related to the `BottomNavigationBar`, but it makes the system nav bar (below space for bottom nav bar,. you custom one or the ones from Flutter) transparent and screen fill the entire area even behind system nav bar and also top status bar (above Flutter's AppBar), so we can see when things scroll behind them too, if nothing covers them, like in this example.
> 
> I can't really see any major flashing on a Pixel 7 Pro emulator. There is odd jumping of the `TextField`, but that is just Flutter's normal a bit crappy behavior. I think there are some Flutter issues about it.
> 
> This would look the same if you remove `FlexColorScheme` and just set the transparent system navbar and edge-to-edge mode with SystemChrome calls.
> 
>  Screen.Recording.2024-10-22.at.16.40.10.mov 
> I tweaked the example a bit, it does not really change anything:
> 
> ```dart
> import 'package:flex_color_scheme/flex_color_scheme.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter/services.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   // This widget is the root of your application.
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       debugShowCheckedModeBanner: false,
>       title: 'Flutter Demo',
>       theme: FlexThemeData.light(
>           scheme: FlexScheme.blue,
>           useMaterial3: true,
>           appBarOpacity: 0.94,
>           subThemesData: const FlexSubThemesData(
>             inputDecoratorBorderType: FlexInputBorderType.outline,
>             inputDecoratorRadius: 12,
>           )),
>       darkTheme: FlexThemeData.dark(
>           scheme: FlexScheme.blue,
>           useMaterial3: true,
>           appBarOpacity: 0.92,
>           subThemesData: const FlexSubThemesData(
>             inputDecoratorBorderType: FlexInputBorderType.outline,
>             inputDecoratorRadius: 12,
>           )),
>       home: const MyHomePage(title: 'Flutter Demo Home Page'),
>     );
>   }
> }
> 
> class MyHomePage extends StatelessWidget {
>   const MyHomePage({super.key, required this.title});
> 
>   final String title;
> 
>   @override
>   Widget build(BuildContext context) {
>     final double topPadding =
>         MediaQuery.paddingOf(context).top + kToolbarHeight;
>     return AnnotatedRegion<SystemUiOverlayStyle>(
>       value: FlexColorScheme.themedSystemNavigationBar(
>         context,
>         systemNavBarStyle: FlexSystemNavBarStyle.transparent,
>       ),
>       child: Scaffold(
>         extendBody: true,
>         extendBodyBehindAppBar: true,
>         appBar: AppBar(
>           title: Text(title),
>         ),
>         bottomNavigationBar: SafeArea(
>           child: Container(
>             decoration: BoxDecoration(
>               color: Theme.of(context).colorScheme.surface,
>               borderRadius: BorderRadius.circular(12),
>               boxShadow: [
>                 BoxShadow(
>                     color: Theme.of(context)
>                         .colorScheme
>                         .outlineVariant
>                         .withOpacity(0.5),
>                     blurRadius: 12),
>               ],
>             ),
>             margin: const EdgeInsets.only(left: 38, right: 38, bottom: 7),
>             padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 4),
>             child: Row(
>               children: [
>                 FilledButton(onPressed: () {}, child: const Text('add')),
>                 FilledButton(onPressed: () {}, child: const Text('add')),
>               ],
>             ),
>           ),
>         ),
>         body: CustomScrollView(
>           slivers: [
>             SliverToBoxAdapter(
>               child: Column(
>                 children: [
>                   SizedBox(height: topPadding),
>                   const ListTile(title: Text('Item more text 1')),
>                   const ListTile(title: Text('Item more text 2')),
>                   const ListTile(title: Text('Item more text 3')),
>                   const ListTile(title: Text('Item more text 4')),
>                   const ListTile(title: Text('Item more text 5')),
>                   const ListTile(title: Text('Item more text 6')),
>                   const ListTile(title: Text('Item more text 7')),
>                   const ListTile(title: Text('Item more text 8')),
>                   const ListTile(title: Text('Item more text 9')),
>                   const ListTile(title: Text('Item more text 10')),
>                   const ListTile(title: Text('Item more text 11')),
>                   const ListTile(title: Text('Item more text 12')),
>                   const ListTile(title: Text('Item more text 13')),
>                   const ListTile(title: Text('Item more text 14')),
>                   const ListTile(title: Text('Item more text 15')),
>                   const ListTile(title: Text('Item more text 16')),
>                   const ListTile(title: Text('Item more text 17')),
>                   const ListTile(title: Text('Item more text 18')),
>                 ],
>               ),
>             ),
>             const SliverToBoxAdapter(
>               child: Padding(
>                 padding: EdgeInsets.all(8.0),
>                 child: TextField(),
>               ),
>             ),
>             const SliverToBoxAdapter(
>               child: SizedBox(height: 100),
>             ),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```

thanks you
