### ISSUE TITLE
🐛 Share Config button links from latest to dev stage

### ISSUE THREAD

**Issue by kay-schecker** [rydmike/flex_color_scheme#263]
If I create a shareable link on 

[https://rydmike.com/flexcolorscheme/themesplayground-latest](https://rydmike.com/flexcolorscheme/themesplayground-latest
)

then I got a link pointing to 

[https://rydmike.com/flexcolorscheme/themesplayground-dev](https://rydmike.com/flexcolorscheme/themesplayground-dev)

**Comment by rydmike** [comment]
Thanks for the report, and oops, need to fix that.

**Comment by rydmike** [comment]
Fixed!

Make sure you refresh the site until you in about see Playground build 06 of FCS v8.0.1

Thanks for the report! 👍🏻 

![Screenshot 2024-11-28 at 23 08 37](https://github.com/user-attachments/assets/80d39e0c-0401-4f51-afcc-0fa037c77698)
