### ISSUE TITLE
How to make the plug-in flex_color_scheme dependent on user installation at run time

### ISSUE THREAD

**Issue by maxfrees** [rydmike/flex_color_scheme#267]
How to make plug-in dependencies dependent on users to install at runtime、

Similar to js

```
"peerDependencies": {
  "sortablejs": "*",
  "@standard-semi/vars": "*",
  "@types/sortablejs": "*",
  "vue": "*"
}
```

I have a flutter project example that introduces its own encapsulated plug-in theme_design. The code is based on flex_color_scheme. How can I allow users to explicitly introduce flex_color_scheme when referencing theme_design plug-in, so that flex_color_scheme in theme_design depends on the flex_color_scheme explicitly referenced by the user?

**Comment by rydmike** [comment]
Hi @maxfrees, I'm not entirely sure I understand the question here, yet at least. But let's discuss it and try to figure it out together 😄 

First off, you cannot dynamically at run time, add dependencies in **Dart**. So any dependency has to be included at app build-time.

You can of course make packages/libraries (used via pub, git or just local files) that depends on other packages and provide new feature or higher level abstractions of them.

So you can for example make your own package that uses `FlexColorScheme` that provides some simpler APIs, that your customers and users can then include in their app.

If you on the other hand are talking about building Flutter apps that users can dynamically modify and change the theme of, that is of course very doable.

The entire **Themes Playground** app is an example of this. With it you are not only making a theme configuration for the **FlexColorScheme** `ThemeData` factory API to copy/paste, but it also dynamically as you do so, it changes the theme of the **Themes Playground** app itself, to the same theme, while you configure the desired theme for you app.

The doc tutorials and examples 2, 3 and 4 are simpler examples of this (starting here https://docs.flexcolorscheme.com/tutorial2). While tutorial 5, is the entire **Themes Playground** app, but it can be a bit overwhelming to jump into.

Please feel free to clarify your question if these replies did not help. I struggled a bit with trying to understand what you wanted to know 😄

**Comment by maxfrees** [comment]
thanks you
