### ISSUE TITLE
[Documentation] improvement of scheme overview

### ISSUE THREAD

**Issue by jlnrrg** [rydmike/flex_color_scheme#4]
I know that you have an overview of the different schemes on your [website](https://rydmike.com/colorscheme), with the scheme name hidden in each picture. But the [overview picture](https://raw.githubusercontent.com/rydmike/flex_color_scheme/master/resources/fcs_all_schemes_24_at_75.png) on [pub.dev](https://pub.dev/packages/flex_color_scheme) has a too low resolution so the names can't be seen. I would encourage to improve the documentation here for better access on choosing a theme.

**Comment by rydmike** [comment]
There are now 4 ways to see the built-in color schemes:

1. The visual "teaser" [overview](https://pub.dev/packages/flex_color_scheme#built-in-color-schemes)
2. The high-res images in the [blog](https://rydmike.com/colorscheme#built-in-color-schemes)
3. By using the live web [example 4](https://rydmike.com/flexcolorscheme4) or [example 5](https://rydmike.com/flexcolorscheme5) where you can select see and try what all the schemes really look like when applied to many different widgets.
4. Via the appendix table in the [documentation](https://pub.dev/packages/flex_color_scheme#appendix-a---built-in-scheme-reference) added to just released version 1.4.0, where you can click to open a high-res phone image of each scheme. It actually uses the images in the article. Sorry, no thumbnails in the table, maybe someday.

Combined these ways should be more than sufficient to find a color scheme. Closing this issue. :)
