### ISSUE TITLE
Upgrade to flutter 3.0.0

### ISSUE THREAD

**Issue by rulim34** [rydmike/flex_color_scheme#53]
When will the flutter 3.0.0 support merged and released to pub.dev?

**Comment by rydmike** [comment]
Hi thanks for the question, it has been a bit slow progress, I simply had to do work on paid work :D 
but it is progressing steadily now, some more info here: 

https://github.com/rydmike/flex_color_scheme/issues/52#issuecomment-1151760058

**Comment by rydmike** [comment]
Closing, this is done via https://github.com/rydmike/flex_color_scheme/pull/58 and in latest release v5.1.0 https://pub.dev/packages/flex_color_scheme/changelog.
