### ISSUE TITLE
Give examples speaking names

### ISSUE THREAD

**Issue by dkbast** [rydmike/flex_color_scheme#61]
The examples in the examples folder are currently numerated - I would suggest giving them speaking names for easier access to "what we are looking for".

BTW Thanks for creating and maintaining this project :-)!

**Comment by rydmike** [comment]
Thanks Damian @dkbast, glad you enjoy the project. With all the pending changes in Flutter SDK theming it is a bit challenging to keep it together nicely during the transition, but so far so good.

We can certainly do this, I added some minor review feedback on your PR.
