### ISSUE TITLE
BottomAppBar taps first item where ever i tap

### ISSUE THREAD

**Issue by mdikcinar** [rydmike/flex_color_scheme#98]
I had spend much of time to find this bug and finally i found the problem is happening when i give the theme with FlexThemeData.

BottomAppBar automaticly taps the first item where ever i tap on the screen.

How to produce:
``` dart
MaterialApp(
      /* theme: ThemeData.light().copyWith(
        useMaterial3: true,
      ), */
      theme: FlexThemeData.light(
        scheme: FlexScheme.amber,
        useMaterial3: true,
      ),
      home: Scaffold(
        bottomNavigationBar: BottomAppBar(
          child: BottomNavigationBar(
            type: BottomNavigationBarType.fixed,
            items: [
              BottomNavigationBarItem(icon: Icon(Icons.abc), label: '1'),
              BottomNavigationBarItem(icon: Icon(Icons.abc), label: '2'),
              BottomNavigationBarItem(icon: Icon(Icons.abc), label: '3'),
            ],
          ),
        ),
      ),
    ),
```

![Nov-16-2022 01-21-03](https://user-images.githubusercontent.com/77580742/202037324-c98054d5-4d25-4891-bdfa-f43bc89606c5.gif)

`Package verison:  flex_color_scheme: 6.0.1
`
```
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-x64, locale en-TR)
    • Flutter version 3.3.8 on channel stable at /Users/mustafa.dikcinar/fvm/versions/3.3.8
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (7 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mustafa.dikcinar/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0
```

**Comment by rydmike** [comment]
Hi @mdikcinar,

Thank you for your report and question.

There is no issue with the `theme` or `FlexThemeData.light` from FlexColorScheme above. You just have to use the `BottomNavigationBar` and Flutter correctly.

You need to tell the `BottomNavigationBar` which index to select by assigning the index of the tapped tab, to its `currentIndex`.

The tapped index you get from its `onTap` callback. That value you can assign to a local state variable, and call `setState` to tell the widget to rebuild.

There is no need to wrap a `BottomNavigationBar` in a `BottomAppBar`, which is another type of bottom area widget. More like an `AppBar` style widget but kept at the bottom. Those two widgets are not really used together, like your wrapped them above. Regardless of that, it would still work, you can try wrapping the corrected sample below with an `BottomAppBar`, it still work, but the `BottomAppBar` is just extra and not needed in this case.

Here is fixed version of your sample:

```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: FlexThemeData.light(scheme: FlexScheme.amber, useMaterial3: true),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int tabItem = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: tabItem,
        onTap: (int tappedIndex) {
          setState(() {
            tabItem = tappedIndex;
          });
        },
        type: BottomNavigationBarType.fixed,
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: '1'),
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: '2'),
          BottomNavigationBarItem(icon: Icon(Icons.abc), label: '3'),
        ],
      ),
    );
  }
}
````

If you really want to use and try `Material 3` (despite it sill having some issues in Flutter 3.3) I recommend using the `NavigationBar` instead of `BottomNavigationBar`, which is the Material 3 style navigation bar.

Here is an example with it too:

```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: FlexThemeData.light(
        scheme: FlexScheme.materialBaseline,
        useMaterial3: true,
        keyColors: const FlexKeyColors(),
        subThemesData: const FlexSubThemesData(),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int tabItem = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: NavigationBar(
        selectedIndex: tabItem,
        onDestinationSelected: (int tappedIndex) {
          setState(() {
            tabItem = tappedIndex;
          });
        },
        destinations: const [
          NavigationDestination(icon: Icon(Icons.home), label: 'Home'),
          NavigationDestination(icon: Icon(Icons.search), label: 'Search'),
          NavigationDestination(icon: Icon(Icons.access_alarm), label: 'Alarm'),
        ],
      ),
    );
  }
}

```

![Screenshot 2022-11-16 at 5 31 46](https://user-images.githubusercontent.com/39990307/202076964-16e742b7-59f0-4772-bb70-deefd7b56e72.png)


Just as another example.

If you are new to Flutter I can recommend some courses to help you get more proficient in Flutter and Dart.

**Comment by mdikcinar** [comment]
Now i figure out the problem is not about Theming, I was know it was so ridiculous but could not see it last night. Thanks for your recommendations but i know how bottom nav works. I deliberately did not keep a state and left it as above because main problem is not that. 
The code bloc above you share also acting same.
![Nov-16-2022 10-01-55](https://user-images.githubusercontent.com/77580742/202108494-1597e6fc-7edf-42a6-b2fb-2fdef62183d7.gif)

**Comment by mdikcinar** [comment]
If i change NavigationBar to BottomNavigationBar everything is working correctly, but if i give FlexThemeData on this situation same bug comes back. lol

```
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      /*theme: FlexThemeData.light(
        scheme: FlexScheme.materialBaseline,
        useMaterial3: true,
        keyColors: const FlexKeyColors(),
        subThemesData: const FlexSubThemesData(),
      ), */
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);
  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  int tabItem = 0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        currentIndex: tabItem,
        onTap: (int tappedIndex) {
          setState(() {
            tabItem = tappedIndex;
          });
        },
        items: const [
          BottomNavigationBarItem(icon: Icon(Icons.home), label: 'Home'),
          BottomNavigationBarItem(icon: Icon(Icons.search), label: 'Search'),
          BottomNavigationBarItem(icon: Icon(Icons.access_alarm), label: 'Alarm'),
        ],
      ),
    );
  }
}
```

**Comment by rydmike** [comment]
Thanks @mdikcinar, now I see what you mean. That is very interesting. Looks like there must be some other issue at play. 

I wish I could repeat it the splash on the first item, but it works fine when I try the above code sample with or without the `FlexColorScheme` based `ThemeData`, so with or without your commented code block.

Looks like this on my end:

| Default theme | Themed |
|----|----|
| ![default-theme](https://user-images.githubusercontent.com/39990307/202176643-d12ca17d-36c7-469f-bfe0-4d95edca5361.gif) | ![themed](https://user-images.githubusercontent.com/39990307/202176597-15d25825-d207-42d9-b049-f3c66dbd7474.gif) |

Enabling Material 3 brings on odd extra ink effect, seen above too, but that happen also with just:

```dart
theme: ThemeData.light(useMaterial3: true),
```

**Comment by rydmike** [comment]
That ink ripple splash issue above should of course not be related to the extra ink ripple you show in your example.

I can however not replicate that, not even if I don't provide onTap or onDestinationSelected in `NavigationBar`, here is one showing that, works as expected, with or without `FlexThemeData`.

![navbar-no-ontap](https://user-images.githubusercontent.com/39990307/202196007-ae147513-f0a6-44b0-b709-fed96dec28a5.gif)

**Comment by mdikcinar** [comment]
When i build the same code today, i noticed everthing works well. I really don't know what triggered that bug last night, but i tried too many thing to fix it and it cost me lot of time :) Thanks for your helps <3
